version: '3.8'

services:
  book_db:
    image: mysql:latest
    container_name: book_db
    environment:
      MYSQL_ROOT_PASSWORD: book@1234
      MYSQL_DATABASE: book_db
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: book_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - backend
    depends_on:
      - book_db

  book_service:
    build: .
    container_name: book_service
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: book_db
    networks:
      - backend
    depends_on:
      book_db:
        condition: service_healthy

networks:
  backend:
    name: backend
    driver: bridge
