spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:book_db}?createDatabaseIfNotExist=true&serverTimezone=${SERVER_TIME_ZONE:Asia/Bangkok}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:book@1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use "create-drop" for testing, "update" for development
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect